openapi: "3.0.0"

info:
  version: "1.0.0"
  title: MCaaS Documentation
  description: |
    # Introduction
    Trip Ninja uses a REST API with requests and responses in JSON format. For development and testing, the pre-production url
    is to be used. Once ready for live use, access to the production url will be provided. <br  />

    Pre-Production URL: TODO

    For security, Trip Ninja’s servers are only accessible from whitelisted IPs. Please contact your account manager to whitelist IPs you
    will be using.

    # Authentication
    Trip Ninja uses Basic Authentication standards. Simply encode your username and password string using base64 and pass it in the
    authorization headers. See the python example below on how this is done. In the example, the payload and API endpoint url are not
    shown.

    Python Example:

    <pre>
    import base64
    auth = base64.b64encode("USERNAME:PASSWORD")
    headers = {
        'authorization': "Basic "+ auth,
    }
    response = requests.post(url, headers=headers, data=json.dumps(payload))
    </pre>

    # Error Codes
    <table>
      <tr><td>400-1001</td><td>Invalid Input</td></tr>
      <tr><td>400-1002</td><td>cabin_class is not valid. Must be one of E, PE, BC, FC, PFC</td></tr>
      <tr><td>400-2001</td><td>Flight dates cannot be in the past</td></tr>
      <tr><td>400-2002</td><td>Arrival date must be after departure date</td></tr>
      <tr><td>400-3001</td><td>itinerary_reference does not exist</td></tr>
      <tr><td>400-3002</td><td>trip_id does not exist</td></tr>
    <table>
  x-logo:
    url: 'https://s3.amazonaws.com/tn-api-docs/tripninja_logo_dev-01.png'
    altText: Trip Ninja logo

paths:
    /markup/:
        post:
            summary: "Markup"
            description: |
                Send an array of itineraries and we will return an array of id and markup pairs corresponding to each itinerary.
                    <h2>Error Codes</h2>
                    <table>
                    <tr><td>400-1001</td><td>Invalid Input</td></tr>
                    <tr><td>400-1002</td><td>cabin_class is not valid. Must be one of E, PE, BC, FC, PFC</td></tr>
                    <tr><td>400-2001</td><td>Flight dates cannot be in the past</td></tr>
                    <tr><td>400-2002</td><td>Arrival date must be after departure date</td></tr>
                    <tr><td>400-3001</td><td>itinerary_reference does not exist</td></tr>
                    <tr><td>400-3002</td><td>trip_id does not exist</td></tr>
                    <table>
            operationId: Markup
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/MarkupPostRequest'
            responses:
                200:
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/MarkupPostResponse'
                400:
                    description: Invalid input
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/MarkupOverrideErrorCodes'
        patch:
            summary: "Markup Override"
            description: |
                This endpoint allows users to override the markup provided before.
            operationId: MarkupOverride
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/MarkupOverrideRequest'
            responses:
                200:
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/MarkupOverrideResponse'
                400:
                    description: Invalid input
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/MarkupOverrideErrorCodes'

    /profile/price/:
        patch:
            summary: "Pricing Profile"
            description: |
                This endpoint allows users to notify every time a price confirmation has been made.
            operationId: PricingProfile
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ProfileRequest'
            responses:
                200:
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ProfileResponse'
                400:
                    description: Invalid input
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ProfileErrorCodes'

    /profile/book/:
        patch:
            summary: "Booking Profile"
            description: |
                This endpoint allows users to notify every time a trip has been booked.
            operationId: BookingProfile
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ProfileRequest'
            responses:
                200:
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ProfileResponse'
                400:
                    description: Invalid input
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ProfileErrorCodes'
    /profile/cancel/:
        patch:
            summary: "Booking Cancellation Profile"
            description: |
                This endpoint allows users to notify every time a booking has been cancelled.
            operationId: BookingCancellationProfile
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ProfileRequest'
            responses:
                200:
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ProfileResponse'
                400:
                    description: Invalid input
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ProfileErrorCodes'

    /profile/ticket/:
        patch:
            summary: "Ticketing Profile"
            description: |
                This endpoint allows users to notify every time a trip has been ticketed.
            operationId: TicketingProfile
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ProfileRequest'
            responses:
                200:
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ProfileResponse'
                400:
                    description: Invalid input
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ProfileErrorCodes'


components:s